# Padroes proibidos em mensagens de commit — source em prepare-commit-msg e commit-msg.
FORBIDDEN_TRAILER='(Co-authored-by:|Co-Authored-By:|Made-with:|Made with |Generated with |cursoragent@cursor\.com)'
# Bloqueia ATRIBUICAO de autoria a ferramenta/IA. Nome de ferramenta como objeto do
# commit ("fix openai client", "update gemini adapter") e permitido; ferramenta como
# autor ("feito com Claude", "generated by Copilot") nao. Ver rules/git.md §4.2.
FORBIDDEN_MSG='(co-authored|co_authored|cursoragent|made.with|generated.(with|by)|\b(by|with|via|por|com|pelo|pela)[[:space:]]+(cursor|claude|copilot|codex|gemini|chatgpt|openai)\b|\b(agente|agentes|ia|ai)\b|inteligencia.artificial|inteligência.artificial)'
